@startuml trabajoPractico


'Clase padre de contribuyente y visualizador

class Visitante {
    registrado: bool
}

class Administrador extends Visitante {
    atenderSolicitud(solicitud: SolicitudEliminacion)
    crearColeccion()
}

class Contribuyente extends Visitante {
    nombre: string
    apellido: string
    edad: int
    validarEdad()
    subirHecho(hecho: Hecho)
    solicitarEliminar(hecho: Hecho)
}

class Visualizador extends Visitante {
    
}

class Coleccion {
    fuenteColeccion : Fuente
    tituloColeccion: string
    descripcionColeccion: string
    criteriosPertenencia: <List> CriterioPertenencia
    hechos: <List> Hecho
    agregarHecho(hecho: Hecho): void
}

class Fuente {
    hechos: <List> Hecho   
}

class Fuente_estatica extends Fuente {
    direccion_archivo_csv: string
}

class Fuente_dinamica extends Fuente {}

' DUDA => Criterios: lista de valores/atributos/lo que sea/ o clase
' Se diagraman las fuentes en el DC? o podemos dejarlo como un atributo
' "Obtención de hechos en lote por archivos CSV, implicancias en el diagrama de clase
' 
' https://www.youtube.com/watch?v=IpDr3I1X7Os
interface CriterioPertenencia {
    cumpleConCriterio(hecho: Hecho) : bool
}

class CriterioTitulo {
    titulo: string
    cumpleConCriterio(hecho: Hecho) : bool
}

class CriterioDescripcion {
    descripcion: string
    cumpleConCriterio(hecho: Hecho) : bool
}

class CriterioCategoria {
    categoria: string
    cumpleConCriterio(hecho: Hecho) : bool
}

class CriterioUbicacion {
    ubicacion: Ubicacion
    cumpleConCriterio(hecho: Hecho) : bool
}

class CriterioFecha {
    fechaInicial: LocalDate
    fechaFinal: LocalDate
    cumpleConCriterio(hecho: Hecho) : bool
}

class CriterioOrigen {
    origen: Origen_Fuente
    cumpleConCriterio(hecho: Hecho) : bool
}

abstract class Hecho {
    titulo: string
    descripcion: string
    categoria: string 
    ubicacion: Ubicacion
    fechaAcontecimiento: LocalDate
    fechaCarga: LocalDate
    origen: Origen_Fuente
    estaOculto : bool
    etiquetas: <List> Etiqueta

    estaRepetido()
}

class Etiqueta {
    descripcion: string
}

class Ubicacion {
    latitud: float
    longitud: float
}

class HechoMultimedia extends Hecho {
    contenidoMultimedia: <List> Formato
}

interface Formato {
    reproducir(): void
}

class Audio {
    duracion: int
    reproducir(): void

}

class Video {
    reproducir(): void

}

class Imagen {
    ancho: float
    alto: float
    reproducir(): void
}

class HechoTextual extends Hecho {
    cuerpo: string
}

class SolicitudEliminacion {
    hecho : Hecho
    justificacion: string
    estado: Estado

    esCorrecta(): bool
}

enum Estado {
    ACEPTADA
    PENDIENTE
    RECHAZADA
}

enum Origen_Fuente {
    ESTATICA 
    DINAMICA
    INTERMEDIARIA
}

' Hecho
Hecho -up-> Etiqueta
Hecho -down-> Origen_Fuente
Hecho <--up- SolicitudEliminacion
Hecho *--right Coleccion
Hecho -up-> Ubicacion
Hecho ---down> CriterioPertenencia


Coleccion --> Fuente
SolicitudEliminacion --left-> Estado
HechoMultimedia -down-> Formato

Contribuyente -- Hecho
Contribuyente -- SolicitudEliminacion
Administrador -down- SolicitudEliminacion  
Visitante <|--down- Administrador
'Administrador -- Coleccion

' Criterios de pertenencia
CriterioPertenencia <|... CriterioTitulo
CriterioPertenencia <|... CriterioDescripcion
CriterioPertenencia <|... CriterioCategoria
CriterioPertenencia <|... CriterioUbicacion
CriterioPertenencia <|... CriterioFecha
CriterioPertenencia <|... CriterioOrigen

' Formato
Formato <|.. Audio
Formato <|.. Video
Formato <|.. Imagen


@enduml

' JUSTIFICACIONES DE: ESTAOCULTO, CRITERIOS PERTENENCIA, VISUALIZADOR, HECHO(CLASE ABSTRACTA), HECHO COMO CLASE ABSTRACTA